// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: fileService.proto

package file

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadReq_Info
	//	*UploadReq_Chunk
	Payload       isUploadReq_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadReq) Reset() {
	*x = UploadReq{}
	mi := &file_fileService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReq) ProtoMessage() {}

func (x *UploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_fileService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReq.ProtoReflect.Descriptor instead.
func (*UploadReq) Descriptor() ([]byte, []int) {
	return file_fileService_proto_rawDescGZIP(), []int{0}
}

func (x *UploadReq) GetPayload() isUploadReq_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadReq) GetInfo() *FileInfo {
	if x != nil {
		if x, ok := x.Payload.(*UploadReq_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *UploadReq) GetChunk() *Chunk {
	if x != nil {
		if x, ok := x.Payload.(*UploadReq_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadReq_Payload interface {
	isUploadReq_Payload()
}

type UploadReq_Info struct {
	Info *FileInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type UploadReq_Chunk struct {
	Chunk *Chunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadReq_Info) isUploadReq_Payload() {}

func (*UploadReq_Chunk) isUploadReq_Payload() {}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientUuid    string                 `protobuf:"bytes,1,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_fileService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fileService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_fileService_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfo) GetClientUuid() string {
	if x != nil {
		return x.ClientUuid
	}
	return ""
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_fileService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_fileService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_fileService_proto_rawDescGZIP(), []int{2}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResp) Reset() {
	*x = UploadResp{}
	mi := &file_fileService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResp) ProtoMessage() {}

func (x *UploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_fileService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResp.ProtoReflect.Descriptor instead.
func (*UploadResp) Descriptor() ([]byte, []int) {
	return file_fileService_proto_rawDescGZIP(), []int{3}
}

func (x *UploadResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadResp) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_fileService_proto protoreflect.FileDescriptor

const file_fileService_proto_rawDesc = "" +
	"\n" +
	"\x11fileService.proto\x12\x04file\"a\n" +
	"\tUploadReq\x12$\n" +
	"\x04info\x18\x01 \x01(\v2\x0e.file.FileInfoH\x00R\x04info\x12#\n" +
	"\x05chunk\x18\x02 \x01(\v2\v.file.ChunkH\x00R\x05chunkB\t\n" +
	"\apayload\"?\n" +
	"\bFileInfo\x12\x1f\n" +
	"\vclient_uuid\x18\x01 \x01(\tR\n" +
	"clientUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1b\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"4\n" +
	"\n" +
	"UploadResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size2`\n" +
	"\x04File\x12-\n" +
	"\x06Upload\x12\x0f.file.UploadReq\x1a\x10.file.UploadResp(\x01\x12)\n" +
	"\bDownload\x12\x0e.file.FileInfo\x1a\v.file.Chunk0\x01B;H\x01Z7github.com/Cheasezz/fileService/proto/fileService/;fileb\x06proto3"

var (
	file_fileService_proto_rawDescOnce sync.Once
	file_fileService_proto_rawDescData []byte
)

func file_fileService_proto_rawDescGZIP() []byte {
	file_fileService_proto_rawDescOnce.Do(func() {
		file_fileService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fileService_proto_rawDesc), len(file_fileService_proto_rawDesc)))
	})
	return file_fileService_proto_rawDescData
}

var (
	file_fileService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
	file_fileService_proto_goTypes  = []any{
		(*UploadReq)(nil),  // 0: file.UploadReq
		(*FileInfo)(nil),   // 1: file.FileInfo
		(*Chunk)(nil),      // 2: file.Chunk
		(*UploadResp)(nil), // 3: file.UploadResp
	}
)
var file_fileService_proto_depIdxs = []int32{
	1, // 0: file.UploadReq.info:type_name -> file.FileInfo
	2, // 1: file.UploadReq.chunk:type_name -> file.Chunk
	0, // 2: file.File.Upload:input_type -> file.UploadReq
	1, // 3: file.File.Download:input_type -> file.FileInfo
	3, // 4: file.File.Upload:output_type -> file.UploadResp
	2, // 5: file.File.Download:output_type -> file.Chunk
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fileService_proto_init() }
func file_fileService_proto_init() {
	if File_fileService_proto != nil {
		return
	}
	file_fileService_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadReq_Info)(nil),
		(*UploadReq_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fileService_proto_rawDesc), len(file_fileService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fileService_proto_goTypes,
		DependencyIndexes: file_fileService_proto_depIdxs,
		MessageInfos:      file_fileService_proto_msgTypes,
	}.Build()
	File_fileService_proto = out.File
	file_fileService_proto_goTypes = nil
	file_fileService_proto_depIdxs = nil
}
